REVENUE_MCAP_SCAPE = ["Nano", "Micro", "Small", "Mid", "Large", "Mega"]

EXCHANGES = ["NYSE", "NASDAQ", "NYSEMKT", "OTC", "BATS", "NYSEARCA"]

STOCK_CATEGORIES = [
    "Domestic Common Stock",
    "Domestic Common Stock Primary Class",
    "ADR Common Stock",
    "Canadian Common Stock",
    "ADR Common Stock Primary Class",
    "Canadian Common Stock Primary Class",
]

COUNTRIES = [
    "U.S.A",
    "China",
    "Canada",
    "Switzerland",
    "United Kingdom",
    "Brazil",
    "Bermuda",
    "Ireland",
    "Netherlands",
    "Colombia",
    "Peru",
    "Singapore",
    "Germany",
    "Hong Kong",
    "Luxembourg",
    "U.S.A.",
    "Australia",
    "Cayman Islands",
    "Chile",
    "Israel",
    "Mexico",
    "United Arab Emirates",
    "Taiwan",
    "Uruguay",
    "Belgium",
    "Denmark",
    "South Africa",
    "India",
    "Panama",
    "Argentina",
    "Puerto Rico",
    "France",
    "Guernsey",
    "Sweden",
    "Japan",
    "Malaysia",
    "Jersey",
    "Monaco",
    "Greece",
    "Republic Of Korea",
    "Cyprus",
    "Italy",
    "Norway",
    "British Virgin Islands",
    "Thailand",
    "Malta",
    "Marshall Islands",
    "Turkey",
    "Jordan",
    "Indonesia",
    "Finland",
    "Bahamas",
    "Kazakhstan",
    "Philippines",
    "Netherlands Antilles",
    "Spain",
    "Ghana",
]

INDICATORS_MAP = {
    "ticker": "Ticker Symbol",
    "table": "Table",
    "sicsector": "SIC Sector",
    "sicindustry": "SIC Industry",
    "siccode": "Standard Industrial Classification (SIC) Code",
    "sector": "Sector",
    "secfilings": "SEC Filings URL",
    "scalerevenue": "Company Scale - Revenue",
    "scalemarketcap": "Company Scale - Market Cap",
    "relatedtickers": "Related Tickers",
    "permaticker": "Permanent Ticker Symbol",
    "name": "Issuer Name",
    "location": "Location",
    "lastupdated": "Last Updated Date",
    "lastquarter": "Last Quarter",
    "lastpricedate": "Last Price Date",
    "isdelisted": "Is Delisted?",
    "industry": "Industry",
    "firstquarter": "First Quarter",
    "firstpricedate": "First Price Date",
    "firstadded": "First Added Date",
    "famasector": "Fama Sector",
    "famaindustry": "Fama Industry",
    "exchange": "Stock Exchange",
    "cusips": "CUSIPs",
    "currency": "Currency",
    "companysite": "Company Website URL",
    "category": "Issuer Category",
    "note": "Notes",
    "date": "Date",
    "contraticker": "Contra Ticker Symbol",
    "contraname": "Contra Issuer Name",
    "action": "Action",
    "volume": "Volume",
    "open": "Open Price - Split Adjusted",
    "low": "Low Price - Split Adjusted",
    "high": "High Price - Split Adjusted",
    "closeunadj": "Close Price - Unadjusted",
    "closeadj": "Close Price - Adjusted for Splits Dividends and Spinoffs",
    "close": "Close Price - Split Adjusted",
    "wntvalue": "Value of Warrant units held (institutional)",
    "wntunits": "Number of Warrant Units held (institutional)",
    # ... (continue adding the rest of the mappings)
}

SECTORS = [
    "Healthcare",
    "Basic Materials",
    "Industrials",
    "Consumer Defensive",
    "Real Estate",
    "Financial Services",
    "Consumer Cyclical",
    "Technology",
    "Energy",
    "Utilities",
    "Communication Services",
]

SIC_SECTOR = [
    "Manufacturing",
    "Finance Insurance And Real Estate",
    "Services",
    "Transportation Communications Electric Gas And Sanitary Service",
    "Retail Trade",
    "Mining",
    "Wholesale Trade",
    "Construction",
    "Agriculture Forestry And Fishing",
]

[
    "Primary Production Of Aluminum",
    "Blank Checks",
    "Services-Educational Services",
    "Pharmaceutical Preparations",
    "Real Estate Investment Trusts",
    "Air Transportation Scheduled",
    "Real Estate",
    "Life Insurance",
    "Services-Equipment Rental & Leasing Nec",
    "Semiconductors & Related Devices",
    "Air-Cond & Warm Air Heatg Equip & Comm & Indl Refrig Equip",
    "Retail-Auto & Home Supply Stores",
    "Electronic Computers",
    "Metal Mining",
    "Air Transportation Nonscheduled",
    "Investment Advice",
    "Switchgear & Switchboard Apparatus",
    "Wholesale-Drugs Proprietaries & Druggists' Sundries",
    "State Commercial Banks",
    "Biological Products (No Disgnostic Substances)",
    "Beverages",
    "Retail-Auto Dealers & Gasoline Stations",
    "In Vitro & In Vivo Diagnostic Substances",
    "Services-To Dwellings & Other Buildings",
    "Services-Commercial Physical & Biological Research",
    "Services-Prepackaged Software",
    "Security Brokers Dealers & Flotation Companies",
    "Fabricated Structural Metal Products",
    "Medicinal Chemicals & Botanical Products",
    "Retail-Catalog & Mail-Order Houses",
    "Services-Business Services Nec",
    "Blankbooks Looseleaf Binders & Bookbindg & Relatd Work",
    "Oil & Gas Field Services Nec",
    "Services-Amusement & Recreation Services",
    "Services-Engineering Services",
    "Fire Marine & Casualty Insurance",
    "Services-Specialty Outpatient Facilities Nec",
    "Aircraft",
    "Retail-Grocery Stores",
    "Special Industry Machinery Nec",
    "Steel Pipe & Tubes",
    "Services-Medical Laboratories",
    "Insurance Agents Brokers & Service",
    "Patent Owners & Lessors",
    "Cutlery Handtools & General Hardware",
    "Construction - Special Trade Contractors",
    "Miscellaneous Chemical Products",
    "Fats & Oils",
    "Electromedical & Electrotherapeutic Apparatus",
    "Miscellaneous Electrical Machinery Equipment & Supplies",
    "Motor Vehicle Parts & Accessories",
    "Services-Computer Processing & Data Preparation",
    "Miscellaneous Transportation Equipment",
    "Services-Detective Guard & Armored Car Services",
    "Services-Computer Programming Data Processing Etc.",
    "Telephone & Telegraph Apparatus",
    "Services-Home Health Care Services",
    "Wholesale-Petroleum & Petroleum Products (No Bulk Stations)",
    "Electric & Other Services Combined",
    "Structural Clay Products",
    "Instruments For Meas & Testing Of Electricity & Elec Signals",
    "Electronic Components Nec",
    "Gold And Silver Ores",
    "Laboratory Analytical Instruments",
    "Heavy Construction Other Than Bldg Const - Contractors",
    "Retail-Family Clothing Stores",
    "Electric Services",
    "Cogeneration Services & Small Power Producers",
    "Wholesale-Durable Goods",
    "Savings Institutions Not Federally Chartered",
    "Surgical & Medical Instruments & Apparatus",
    "Accident & Health Insurance",
    "Grain Mill Products",
    "Farm Machinery & Equipment",
    "Agricultural Chemicals",
    "Agricultural Services",
    "Services-Management Consulting Services",
    "Services-Misc Health & Allied Services Nec",
    "Federal & Federally-Sponsored Credit Agencies",
    "Services-Computer Programming Services",
    "Surety Insurance",
    "Prefabricated Metal Buildings & Components",
    "Agricultural Production-Crops",
    "Miscellaneous Manufacturing Industries",
    "Services-Miscellaneous Equipment Rental & Leasing",
    "Services-Computer Integrated Systems Design",
    "Finance Lessors",
    "Orthopedic Prosthetic & Surgical Appliances & Supplies",
    "Finance Services",
    "General Industrial Machinery & Equipment Nec",
    "Broadwoven Fabric Mills Man Made Fiber & Silk",
    "Aircraft & Parts",
    "Radio & Tv Broadcasting & Communications Equipment",
    "Aircraft Parts & Auxiliary Equipment Nec",
    "Services-Offices & Clinics Of Doctors Of Medicine",
    "Air Courier Services",
    "Wholesale-Machinery Equipment & Supplies",
    "Insurance Carriers Nec",
    "Guided Missiles & Space Vehicles & Parts",
    "Bottled & Canned Soft Drinks & Carbonated Waters",
    "Plastic Materials Synth Resins & Nonvulcan Elastomers",
    "Ophthalmic Goods",
    "Hospital & Medical Service Plans",
    "Retail-Retail Stores Nec",
    "Computer Communications Equipment",
    "Computer Peripheral Equipment Nec",
    "Communications Equipment Nec",
    "Crude Petroleum & Natural Gas",
    "Services-Skilled Nursing Care Facilities",
    "National Commercial Banks",
    "Wholesale-Industrial Machinery & Equipment",
    "Industrial Organic Chemicals",
    "Natural Gas Transmission",
    "Metal Cans",
    "Services-Motion Picture Theaters",
    "Cable & Other Pay Television Services",
    "Motors & Generators",
    "Services-Help Supply Services",
    "Telephone Communications (No Radiotelephone)",
    "Bituminous Coal & Lignite Surface Mining",
    "Wholesale-Jewelry Watches Precious Stones & Metals",
    "Tires & Inner Tubes",
    "Truck & Bus Bodies",
    "Millwood Veneer Plywood & Structural Wood Members",
    "Wholesale-Farm Product Raw Materials",
    "Communications Services Nec",
    "Services-Advertising",
    "Services-Advertising Agencies",
    "Household Appliances",
    "Ordnance & Accessories (No Vehicles/Guided Missiles)",
    "Pumps & Pumping Equipment",
    "Industrial Inorganic Chemicals",
    "Services-Miscellaneous Business Services",
    "Electronic Connectors",
    "Glass Products Made Of Purchased Glass",
    "Drawing & Insulating Of Nonferrous Wire",
    "Fishing Hunting And Trapping",
    "Secondary Smelting & Refining Of Nonferrous Metals",
    "Refrigeration & Service Industry Machinery",
    "Services-Mailing Reproduction Commercial Art & Photography",
    "Trucking (No Local)",
    "Investors Nec",
    "Retail-Eating Places",
    "Plastics Products Nec",
    "Services-Miscellaneous Repair Services",
    "Title Insurance",
    "Retail-Furniture Stores",
    "Retail-Convenience Stores",
    "Real Estate Operators (No Developers) & Lessors",
    "Household Audio & Video Equipment",
    "Rolling Drawing & Extruding Of Nonferrous Metals",
    "Water Supply",
    "Motor Vehicles & Passenger Car Bodies",
    "Wholesale-Electronic Parts & Equipment Nec",
    "Deep Sea Foreign Transportation Of Freight",
    "Wholesale-Chemicals & Allied Products",
    "Retail-Miscellaneous Shopping Goods Stores",
    "Wholesale-Lumber & Other Construction Materials",
    "Airports Flying Fields & Airport Terminal Services",
    "Construction Machinery & Equip",
    "Steel Works Blast Furnaces & Rolling Mills (Coke Ovens)",
    "Transportation Services",
    "Hotels & Motels",
    "Electric Housewares & Fans",
    "Services-Nursing & Personal Care Facilities",
    "Personal Credit Institutions",
    "Mining & Quarrying Of Nonmetallic Minerals (No Fuels)",
    "Natural Gas Distribution",
    "Radio Broadcasting Stations",
    "Loan Brokers",
    "Electric Lighting & Wiring Equipment",
    "Commercial Banks Nec",
    "Converted Paper & Paperboard Prods (No Contaners/Boxes)",
    "Refuse Systems",
    "Savings Institution Federally Chartered",
    "Periodicals: Publishing Or Publishing & Printing",
    "Paints Varnishes Lacquers Enamels & Allied Prods",
    "Miscellaneous Fabricated Metal Products",
    "Retail-Home Furniture Furnishings & Equipment Stores",
    "Games Toys & Children'S Vehicles (No Dolls & Bicycles)",
    "Services-Health Services",
    "Retail-Hobby Toy & Game Shops",
    "Retail-Women'S Clothing Stores",
    "Retail-Radio Tv & Consumer Electronics Stores",
    "Engines & Turbines",
    "Arrangement Of Transportation Of Freight & Cargo",
    "Chemicals & Allied Products",
    "Electrical Industrial Apparatus",
    "Real Estate Agents & Managers (For Others)",
    "Electronic Coils Transformers & Other Inductors",
    "Trucking & Courier Services (No Air)",
    "Services-Child Day Care Services",
    "X-Ray Apparatus & Tubes & Related Irradiation Apparatus",
    "Security & Commodity Brokers Dealers Exchanges & Services",
    "Retail-Jewelry Stores",
    "Food And Kindred Products",
    "Printed Circuit Boards",
    "Retail-Variety Stores",
    "Dental Equipment & Supplies",
    "Water Transportation",
    "Natural Gas Transmisison & Distribution",
    "Apparel & Other Finishd Prods Of Fabrics & Similar Matl",
    "Short-Term Business Credit Institutions",
    "Oil & Gas Field Machinery & Equipment",
    "Retail-Lumber & Other Building Materials Dealers",
    "Totalizing Fluid Meters & Counting Devices",
    "Operators Of Nonresidential Buildings",
    "Heating Equipment Except Electric & Warm Air Furnaces",
    "Retail-Nonstore Retailers",
    "Miscellaneous Primary Metal Products",
    "Retail-Shoe Stores",
    "Drilling Oil & Gas Wells",
    "Petroleum Refining",
    "Services-Computer Rental & Leasing",
    "Motorcycles Bicycles & Parts",
    "Canned Frozen & Preservd Fruit Veg & Food Specialties",
    "Meat Packing Plants",
    "Sausages & Other Prepared Meat Products",
    "Jewelry Silverware & Plated Ware",
    "Retail-Eating & Drinking Places",
    "Wood Household Furniture (No Upholstered)",
    "Prepared Fresh Or Frozen Fish & Seafoods",
    "Cigarettes",
    "Malt Beverages",
    "Retail-Department Stores",
    "Nonferrous Foundries (Castings)",
    "Wholesale-Lumber Plywood Millwork & Wood Panels",
    "Operative Builders",
    "Photographic Equipment & Supplies",
    "Footwear (No Rubber)",
    "Agricultural Prod-Livestock & Animal Specialties",
    "Optical Instruments & Lenses",
    "Services-Auto Rental & Leasing (No Drivers)",
    "Miscellaneous Metal Ores",
    "Services-Miscellaneous Amusement & Recreation",
    "Plastic Material Synth Resin/Rubber Cellulos (No Glass)",
    "Industrial & Commercial Fans & Blowers & Air Purifing Equip",
    "Bituminous Coal & Lignite Mining",
    "Wholesale-Miscellaneous Nondurable Goods",
    "Electronic Components & Accessories",
    "Industrial Instruments For Measurement Display And Control",
    "Soap Detergents Cleang Preparations Perfumes Cosmetics",
    "Services-Racing Including Track Operation",
    "Wholesale-Groceries General Line",
    "Hazardous Waste Management",
    "Radiotelephone Communications",
    "Construction Mining & Materials Handling Machinery & Equip",
    "Services-Video Tape Rental",
    "Retail-Drug Stores And Proprietary Stores",
    "Perfumes Cosmetics & Other Toilet Preparations",
    "Sporting & Athletic Goods Nec",
    "Wholesale-Computers & Peripheral Equipment & Software",
    "Gas & Other Services Combined",
    "Paperboard Mills",
    "Wholesale-Professional & Commercial Equipment & Supplies",
    "Specialty Cleaning Polishing And Sanitation Preparations",
    "Commercial Printing",
    "Railroads Line-Haul Operating",
    "Wholesale-Durable Goods Nec",
    "Search Detection Navagation Guidance Aeronautical Sys",
    "Household Furniture",
    "Cement Hydraulic",
    "Leather & Leather Products",
    "Pottery & Related Products",
    "Lessors Of Real Property Nec",
    "Services-Legal Services",
    "Telegraph & Other Message Communications",
    "Rubber & Plastics Footwear",
    "Broadwoven Fabric Mills Cotton",
    "Fabricated Rubber Products Nec",
    "Services-Allied To Motion Picture Production",
    "Cut Stone & Stone Products",
    "Services-Personal Services",
    "Adhesives & Sealants",
    "Men'S & Boys' Furnishgs Work Clothg & Allied Garments",
    "Calculating & Accounting Machines (No Electronic Computers)",
    "Retail-Apparel & Accessory Stores",
    "Wholesale-Groceries & Related Products",
    "Services-Motion Picture & Video Tape Production",
    "Mobile Homes",
    "Hotels Rooming Houses Camps & Other Lodging Places",
    "Metalworkg Machinery & Equipment",
    "Misc Industrial & Commercial Machinery & Equipment",
    "Services-General Medical & Surgical Hospitals Nec",
    "Newspapers: Publishing Or Publishing & Printing",
    "Local & Suburban Transit & Interurban Hwy Passenger Trans",
    "Pipe Lines (No Natural Gas)",
    "Wholesale-Apparel Piece Goods & Notions",
    "Services-Consumer Credit Reporting Collection Agencies",
    "Retail-Food Stores",
    "Services-Automotive Repair Services & Parking",
    "Paperboard Containers & Boxes",
    "Oil & Gas Field Exploration Services",
    "Carpets & Rugs",
    "Water Sewer Pipeline Comm & Power Line Construction",
    "Manifold Business Forms",
    "Functions Related To Depository Banking Nec",
    "General Industrial Machinery & Equipment",
    "Services-Hospitals",
    "Electrical Work",
    "Electronic & Other Electrical Equipment (No Computer Equip)",
    "Wholesale-Electrical Apparatus & Equipment Wiring Supplies",
    "Lumber & Wood Products (No Furniture)",
    "Television Broadcasting Stations",
    "Services-Management Services",
    "Retail-Miscellaneous Retail",
    "Canned Fruits Veg Preserves Jams & Jellies",
    "Miscellaneous Food Preparations & Kindred Products",
    "Measuring & Controlling Devices Nec",
    "Retail-Building Materials Hardware Garden Supply",
    "General Bldg Contractors - Residential Bldgs",
    "Wholesale-Hardware & Plumbing & Heating Equipment & Supplies",
    "Heating Equip Except Elec & Warm Air; & Plumbing Fixtures",
    "Wholesale-Petroleum Bulk Stations & Terminals",
    "Mortgage Bankers & Loan Correspondents",
    "Services-Engineering Accounting Research Management",
    "Watches Clocks Clockwork Operated Devices/Parts",
    "Steel Works Blast Furnaces & Rolling & Finishing Mills",
    "Sugar & Confectionery Products",
    "Ship & Boat Building & Repairing",
    "Wholesale-Metals Service Centers & Offices",
    "Railroad Equipment",
    "Wholesale-Metals & Minerals (No Petroleum)",
    "Metal Shipping Barrels Drums Kegs & Pails",
    "Women'S Misses' Children'S & Infants' Undergarments",
    "Metal Doors Sash Frames Moldings & Trim",
    "Paper Mills",
    "Retail-Computer & Computer Software Stores",
    "Wholesale-Motor Vehicle Supplies & New Parts",
    "Primary Smelting & Refining Of Nonferrous Metals",
    "Fabricated Plate Work (Boiler Shops)",
    "Sanitary Services",
    "Aircraft Engines & Engine Parts",
    "Services-Direct Mail Advertising Services",
    "Office Furniture (No Wood)",
    "Computer & Office Equipment",
    "Services-Services Nec",
    "Wholesale-Medical Dental & Hospital Equipment & Supplies",
    "Services-Employment Agencies",
    "Industrial Trucks Tractors Trailors & Stackers",
    "Poultry Slaughtering And Processing",
    "Partitions Shelvg Lockers & Office & Store Fixtures",
    "Operators Of Apartment Buildings",
    "Land Subdividers & Developers (No Cemeteries)",
    "Miscellaneous Business Credit Institution",
    "Special Industry Machinery (No Metalworking Machinery)",
    "Concrete Products Except Block & Brick",
    "Women'S Misses' And Juniors Outerwear",
    "Cookies & Crackers",
    "Laboratory Apparatus & Furniture",
    "Machine Tools Metal Cutting Types",
    "Printing Trades Machinery & Equipment",
    "Retail-Record & Prerecorded Tape Stores",
    "Miscellaneous Products Of Petroleum & Coal",
    "Wholesale-Motor Vehicles & Motor Vehicle Parts & Supplies",
    "Wholesale-Hardware",
    "Services-Membership Sports & Recreation Clubs",
    "Dairy Products",
    "Miscellaneous Plastics Products",
    "Oil Royalty Traders",
    "Dolls & Stuffed Toys",
    "Metal Forgings & Stampings",
    "Pulp Mills",
    "Electric Gas & Sanitary Services",
    "Wholesale-Beer Wine & Distilled Alcoholic Beverages",
    "Phonograph Records & Prerecorded Audio Tapes & Disks",
    "Office Furniture",
    "Mineral Royalty Traders",
    "Services-Testing Laboratories",
    "Ball & Roller Bearings",
    "Gaskets Packg & Sealg Devices & Rubber & Plastics Hose",
    "Computer Storage Devices",
    "Coating Engraving & Allied Services",
    "Power Distribution & Specialty Transformers",
    "Abrasive Asbestos & Misc Nonmetallic Mineral Prods",
    "Glass Containers",
    "Office Machines Nec",
    "Wholesale-Misc Durable Goods",
    "Books: Publishing Or Publishing & Printing",
    "Plastics Foil & Coated Paper Bags",
    "Miscellaneous Publishing",
    "Unsupported Plastics Film & Sheet",
    "Commodity Contracts Brokers & Dealers",
    "Flat Glass",
    "Motor Homes",
    "Auto Controls For Regulating Residential & Comml Environments",
    "Ice Cream & Frozen Desserts",
    "Tobacco Products",
    "General Bldg Contractors - Nonresidential Bldgs",
    "Lawn & Garden Tractors & Home Lawn & Gardens Equip",
    "Bakery Products",
    "Textile Mill Products",
    "Sawmills & Planting Mills General",
    "Railroad Switching & Terminal Establishments",
    "Public Bldg & Related Furniture",
    "Wholesale-Paper & Paper Products",
    "Services-Facilities Support Management Services",
    "Plastics Foam Products",
    "Truck Trailers",
]

INDUSTRIES = [
    "Diagnostics & Research",
    "Aluminum",
    "Shell Companies",
    "Education & Training Services",
    "Biotechnology",
    "REIT - Mortgage",
    "Airlines",
    "Asset Management",
    "Insurance - Life",
    "Specialty Retail",
    "Semiconductors",
    "Building Products & Equipment",
    "Consumer Electronics",
    "REIT - Diversified",
    "Gold",
    "Airports & Air Services",
    "Electrical Equipment & Parts",
    "Drug Manufacturers - General",
    "Medical Distribution",
    "Banks - Regional",
    "Beverages - Brewers",
    "Auto & Truck Dealerships",
    "Specialty Business Services",
    "Internet Content & Information",
    "Software - Application",
    "Medical Devices",
    "Capital Markets",
    "Infrastructure Operations",
    "Drug Manufacturers - Specialty & Generic",
    "Health Information Services",
    "Business Equipment & Supplies",
    "Oil & Gas Equipment & Services",
    "Gambling",
    "Engineering & Construction",
    "Insurance - Diversified",
    "Medical Care Facilities",
    "Aerospace & Defense",
    "Grocery Stores",
    "Software - Infrastructure",
    "Semiconductor Equipment & Materials",
    "Information Technology Services",
    "Steel",
    "Insurance - Specialty",
    "Household & Personal Products",
    "REIT - Retail",
    "Building Materials",
    "Pollution & Treatment Controls",
    "Farm Products",
    "Utilities - Renewable",
    "Auto Parts",
    "Staffing & Employment Services",
    "Security & Protection Services",
    "Advertising Agencies",
    "Communication Equipment",
    "Oil & Gas Refining & Marketing",
    "Utilities - Regulated Electric",
    "Real Estate - Development",
    "Apparel Retail",
    "Utilities - Diversified",
    "Electronics & Computer Distribution",
    "REIT - Specialty",
    "Insurance - Property & Casualty",
    "Silver",
    "Entertainment",
    "Farm & Heavy Construction Machinery",
    "Credit Services",
    "REIT - Hotel & Motel",
    "Specialty Industrial Machinery",
    "Textile Manufacturing",
    "REIT - Residential",
    "Integrated Freight & Logistics",
    "Industrial Distribution",
    "Insurance Brokers",
    "Internet Retail",
    "Beverages - Non-Alcoholic",
    "Medical Instruments & Supplies",
    "Rental & Leasing Services",
    "Specialty Chemicals",
    "Healthcare Plans",
    "Computer Hardware",
    "Metal Fabrication",
    "Oil & Gas E&P",
    "Oil & Gas Midstream",
    "Packaging & Containers",
    "Broadcasting",
    "Other Industrial Metals & Mining",
    "Electronic Components",
    "Telecom Services",
    "Thermal Coal",
    "Auto Manufacturers",
    "Furnishings Fixtures & Appliances",
    "Food Distribution",
    "Leisure",
    "Chemicals",
    "Waste Management",
    "Trucking",
    "Restaurants",
    "REIT - Office",
    "Footwear & Accessories",
    "Coking Coal",
    "Home Improvement Retail",
    "Utilities - Regulated Water",
    "Department Stores",
    "Solar",
    "Marine Shipping",
    "Mortgage Finance",
    "Resorts & Casinos",
    "Utilities - Regulated Gas",
    "Electronic Gaming & Multimedia",
    "Other Precious Metals & Mining",
    "Agricultural Inputs",
    "Real Estate Services",
    "Banks - Diversified",
    "Consulting Services",
    "Conglomerates",
    "Lumber & Wood Production",
    "Beverages - Wineries & Distilleries",
    "Personal Services",
    "Luxury Goods",
    "Packaged Foods",
    "Discount Stores",
    "Pharmaceutical Retailers",
    "Travel Services",
    "Scientific & Technical Instruments",
    "Insurance - Reinsurance",
    "Oil & Gas Drilling",
    "Oil & Gas Integrated",
    "Tobacco",
    "Residential Construction",
    "Financial Data & Stock Exchanges",
    "Uranium",
    "Real Estate - Diversified",
    "REIT - Healthcare Facilities",
    "Lodging",
    "Paper & Paper Products",
    "Railroads",
    "REIT - Industrial",
    "Apparel Manufacturing",
    "Tools & Accessories",
    "Recreational Vehicles",
    "Publishing",
    "Industrial Metals & Minerals",
    "Copper",
    "Confectioners",
    "Financial Conglomerates",
    "Furnishings",
    "Utilities - Independent Power Producers",
    "Diversified Industrials",
    "Drug Manufacturers - Major",
    "Savings & Cooperative Banks",
    "Computer Systems",
    "Shipping & Ports",
]
